"""
📝 Text Summarization Page
Abstractive summarization using BART (EN) and mT5 (PT-BR) via HF Inference API.
"""

import streamlit as st

from utils.config import SUMMARIZATION_MODELS, EXAMPLE_TEXTS
from utils.hf_client import safe_summarize

# ─── Sidebar Controls ────────────────────────────────────────────────────────

st.header("📝 Text Summarization")
st.markdown(
    "Paste your text below and get an **abstractive summary** generated by "
    "transformer models. Choose your language and adjust the summary length."
)

with st.sidebar:
    st.markdown("### ⚙️ Settings")

    language = st.selectbox(
        "Language",
        options=list(SUMMARIZATION_MODELS.keys()),
        index=0,
        help="Select the language of your input text.",
    )

    model_name = SUMMARIZATION_MODELS[language]
    st.caption(f"**Model:** `{model_name}`")

    st.markdown("---")

    def _load_example():
        st.session_state["summ_input"] = EXAMPLE_TEXTS["summarization"][language]

    st.button("📋 Load example text", on_click=_load_example)

# ─── Main Content ────────────────────────────────────────────────────────────

input_text = st.text_area(
    "Input text",
    height=250,
    placeholder="Paste your text here...",
    label_visibility="collapsed",
    key="summ_input",
)

# ─── Summarize ───────────────────────────────────────────────────────────────

if st.button("🚀 Summarize", type="primary", use_container_width=True):
    if not input_text.strip():
        st.warning("Please enter some text to summarize.")
    elif len(input_text.split()) < 20:
        st.warning("Text is too short for meaningful summarization. Please provide at least 20 words.")
    else:
        with st.spinner("Generating summary... This may take a moment if the model is loading."):
            summary = safe_summarize(
                text=input_text,
                model=model_name,
            )

        if summary:
            st.markdown("### 📄 Summary")
            st.success(summary)

            # ── Metrics ──────────────────────────────────────────────
            st.markdown("### 📊 Metrics")
            original_words = len(input_text.split())
            summary_words = len(summary.split())
            compression = (
                round((1 - summary_words / original_words) * 100, 1)
                if original_words > 0
                else 0
            )

            m1, m2, m3 = st.columns(3)
            m1.metric("Original words", f"{original_words:,}")
            m2.metric("Summary words", f"{summary_words:,}")
            m3.metric("Compression ratio", f"{compression}%")

            # ── Model info ───────────────────────────────────────────
            with st.expander("ℹ️ About this model"):
                if language == "English":
                    st.markdown(
                        """
                        **BART-large-CNN** (`facebook/bart-large-cnn`) is a sequence-to-sequence
                        model fine-tuned on the CNN/DailyMail dataset for abstractive summarization.

                        - Architecture: BART (Bidirectional and Auto-Regressive Transformers)
                        - Parameters: ~406M
                        - Training data: CNN/DailyMail news articles
                        - [Model card on Hugging Face](https://huggingface.co/facebook/bart-large-cnn)
                        """
                    )
                else:
                    st.markdown(
                        """
                        **PTT5-base-summ-xlsum** (`recogna-nlp/ptt5-base-summ-xlsum`) is a T5 model
                        fine-tuned for Portuguese summarization on the XLSum dataset.

                        - Architecture: T5 (Text-to-Text Transfer Transformer)
                        - Base: PTT5 (pre-trained on BrWac Portuguese corpus)
                        - Training data: XLSum (Portuguese subset)
                        - [Model card on Hugging Face](https://huggingface.co/recogna-nlp/ptt5-base-summ-xlsum)
                        """
                    )
